import Link from "next/link";
import "./globals.css";
// import "./page.module.css";

import { Inter } from "next/font/google";
import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <div className=" mt-[100px]  m-auto font-semibold w-[90%]">
          <Link href="/blog"> Blog Page</Link>
        </div>
      </body>
    </html>
  );
}
